image:
  repository: ghcr.io/xenitab/node-ttl
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  #fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

service:
  probe:
    port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

nodeTtl:
  interval: 10m
  statusConfigMapName: cluster-autoscaler-status
  statusConfigMapNamespace: cluster-autoscaler