{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "node-ttl.fullname" . }}-allow-egress
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "node-ttl.fullname" . }}-allow-scraping
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: prometheus
    ports:
    - port: {{ .Values.service.metrics.port }}
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
