apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-ttl.fullname" . }}
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-ttl.fullname" . }}
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-ttl.fullname" . }}
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-ttl.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "node-ttl.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "node-ttl.fullname" . }}
  namespace: {{ .Values.nodeTtl.statusConfigMapNamespace }}
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: [{{ .Values.nodeTtl.statusConfigMapName }}]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "node-ttl.fullname" . }}
  namespace: {{ .Values.nodeTtl.statusConfigMapNamespace }}
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "node-ttl.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "node-ttl.fullname" . }}
  namespace: {{ .Release.Namespace }}
