apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-ttl.fullname" . }}
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-ttl.fullname" . }}
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-ttl.fullname" . }}
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-ttl.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "node-ttl.fullname" . }}
    namespace: {{ .Release.Namespace }}
