apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-ttl.fullname" . }}
  labels:
    {{- include "node-ttl.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "node-ttl.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
